// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: mgidEmployee.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Employee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Salary float32 `protobuf:"fixed32,2,opt,name=salary,proto3" json:"salary,omitempty"`
	Yob    int32   `protobuf:"varint,3,opt,name=yob,proto3" json:"yob,omitempty"`
}

func (x *Employee) Reset() {
	*x = Employee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Employee) GetSalary() float32 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *Employee) GetYob() int32 {
	if x != nil {
		return x.Yob
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{1}
}

type GetImitatedTimeoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetImitatedTimeoutRequest) Reset() {
	*x = GetImitatedTimeoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImitatedTimeoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImitatedTimeoutRequest) ProtoMessage() {}

func (x *GetImitatedTimeoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImitatedTimeoutRequest.ProtoReflect.Descriptor instead.
func (*GetImitatedTimeoutRequest) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{2}
}

type GetImitatedTimeoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetImitatedTimeoutResponse) Reset() {
	*x = GetImitatedTimeoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImitatedTimeoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImitatedTimeoutResponse) ProtoMessage() {}

func (x *GetImitatedTimeoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImitatedTimeoutResponse.ProtoReflect.Descriptor instead.
func (*GetImitatedTimeoutResponse) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{3}
}

type GetSortedEmployeesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *GetSortedEmployeesRequest) Reset() {
	*x = GetSortedEmployeesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSortedEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSortedEmployeesRequest) ProtoMessage() {}

func (x *GetSortedEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSortedEmployeesRequest.ProtoReflect.Descriptor instead.
func (*GetSortedEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{4}
}

func (x *GetSortedEmployeesRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type GetSortedEmployeesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Employee []*Employee `protobuf:"bytes,1,rep,name=employee,proto3" json:"employee,omitempty"`
}

func (x *GetSortedEmployeesResponse) Reset() {
	*x = GetSortedEmployeesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSortedEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSortedEmployeesResponse) ProtoMessage() {}

func (x *GetSortedEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSortedEmployeesResponse.ProtoReflect.Descriptor instead.
func (*GetSortedEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{5}
}

func (x *GetSortedEmployeesResponse) GetEmployee() []*Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type GetEldestEmployeeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetEldestEmployeeRequest) Reset() {
	*x = GetEldestEmployeeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEldestEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEldestEmployeeRequest) ProtoMessage() {}

func (x *GetEldestEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEldestEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetEldestEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{6}
}

type GetEldestEmployeeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Employee *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
}

func (x *GetEldestEmployeeResponse) Reset() {
	*x = GetEldestEmployeeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEldestEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEldestEmployeeResponse) ProtoMessage() {}

func (x *GetEldestEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEldestEmployeeResponse.ProtoReflect.Descriptor instead.
func (*GetEldestEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{7}
}

func (x *GetEldestEmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type GetMedianOfSalariesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMedianOfSalariesRequest) Reset() {
	*x = GetMedianOfSalariesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedianOfSalariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedianOfSalariesRequest) ProtoMessage() {}

func (x *GetMedianOfSalariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedianOfSalariesRequest.ProtoReflect.Descriptor instead.
func (*GetMedianOfSalariesRequest) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{8}
}

type GetMedianOfSalariesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MedianOfSalary float32 `protobuf:"fixed32,1,opt,name=medianOfSalary,proto3" json:"medianOfSalary,omitempty"`
}

func (x *GetMedianOfSalariesResponse) Reset() {
	*x = GetMedianOfSalariesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedianOfSalariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedianOfSalariesResponse) ProtoMessage() {}

func (x *GetMedianOfSalariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedianOfSalariesResponse.ProtoReflect.Descriptor instead.
func (*GetMedianOfSalariesResponse) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{9}
}

func (x *GetMedianOfSalariesResponse) GetMedianOfSalary() float32 {
	if x != nil {
		return x.MedianOfSalary
	}
	return 0
}

type GetAverageOfSalariesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAverageOfSalariesRequest) Reset() {
	*x = GetAverageOfSalariesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAverageOfSalariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageOfSalariesRequest) ProtoMessage() {}

func (x *GetAverageOfSalariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageOfSalariesRequest.ProtoReflect.Descriptor instead.
func (*GetAverageOfSalariesRequest) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{10}
}

type GetAverageOfSalariesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AverageOfSalary float32 `protobuf:"fixed32,1,opt,name=averageOfSalary,proto3" json:"averageOfSalary,omitempty"`
}

func (x *GetAverageOfSalariesResponse) Reset() {
	*x = GetAverageOfSalariesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAverageOfSalariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageOfSalariesResponse) ProtoMessage() {}

func (x *GetAverageOfSalariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageOfSalariesResponse.ProtoReflect.Descriptor instead.
func (*GetAverageOfSalariesResponse) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{11}
}

func (x *GetAverageOfSalariesResponse) GetAverageOfSalary() float32 {
	if x != nil {
		return x.AverageOfSalary
	}
	return 0
}

type GetHighestPaidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHighestPaidRequest) Reset() {
	*x = GetHighestPaidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHighestPaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighestPaidRequest) ProtoMessage() {}

func (x *GetHighestPaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighestPaidRequest.ProtoReflect.Descriptor instead.
func (*GetHighestPaidRequest) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{12}
}

type GetHighestPaidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Employee *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
}

func (x *GetHighestPaidResponse) Reset() {
	*x = GetHighestPaidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgidEmployee_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHighestPaidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighestPaidResponse) ProtoMessage() {}

func (x *GetHighestPaidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mgidEmployee_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighestPaidResponse.ProtoReflect.Descriptor instead.
func (*GetHighestPaidResponse) Descriptor() ([]byte, []int) {
	return file_mgidEmployee_proto_rawDescGZIP(), []int{13}
}

func (x *GetHighestPaidResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

var File_mgidEmployee_proto protoreflect.FileDescriptor

var file_mgidEmployee_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x67, 0x69, 0x64, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x48, 0x0a, 0x08, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61,
	0x6c, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x79, 0x6f, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1b, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x69, 0x74, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x49, 0x6d, 0x69, 0x74, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x31, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x53,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x48, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x65, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x08, 0x65, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x45, 0x6c, 0x64, 0x65,
	0x73, 0x74, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x47, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x45, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a,
	0x0a, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x52, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x4f, 0x66, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x6e, 0x4f, 0x66, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x6e, 0x4f, 0x66, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x4f, 0x66, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x22,
	0x1d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4f, 0x66, 0x53,
	0x61, 0x6c, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48,
	0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4f, 0x66, 0x53, 0x61,
	0x6c, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4f, 0x66, 0x53, 0x61, 0x6c, 0x61, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x4f, 0x66, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x48,
	0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x50, 0x61, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x44, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x50,
	0x61, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x65,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x08, 0x65,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x32, 0x98, 0x04, 0x0a, 0x0f, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x49, 0x6d, 0x69, 0x74, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x69, 0x74,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x59, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x45, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x12, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6c, 0x64, 0x65,
	0x73, 0x74, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6c, 0x64, 0x65,
	0x73, 0x74, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x6e, 0x4f, 0x66, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x4f, 0x66, 0x53, 0x61,
	0x6c, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x4f, 0x66,
	0x53, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5f, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x4f, 0x66, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4f, 0x66, 0x53, 0x61,
	0x6c, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4f,
	0x66, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73,
	0x74, 0x50, 0x61, 0x69, 0x64, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x50, 0x61, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x69, 0x67,
	0x68, 0x65, 0x73, 0x74, 0x50, 0x61, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mgidEmployee_proto_rawDescOnce sync.Once
	file_mgidEmployee_proto_rawDescData = file_mgidEmployee_proto_rawDesc
)

func file_mgidEmployee_proto_rawDescGZIP() []byte {
	file_mgidEmployee_proto_rawDescOnce.Do(func() {
		file_mgidEmployee_proto_rawDescData = protoimpl.X.CompressGZIP(file_mgidEmployee_proto_rawDescData)
	})
	return file_mgidEmployee_proto_rawDescData
}

var file_mgidEmployee_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_mgidEmployee_proto_goTypes = []interface{}{
	(*Employee)(nil),                     // 0: grpc.Employee
	(*Empty)(nil),                        // 1: grpc.Empty
	(*GetImitatedTimeoutRequest)(nil),    // 2: grpc.GetImitatedTimeoutRequest
	(*GetImitatedTimeoutResponse)(nil),   // 3: grpc.GetImitatedTimeoutResponse
	(*GetSortedEmployeesRequest)(nil),    // 4: grpc.GetSortedEmployeesRequest
	(*GetSortedEmployeesResponse)(nil),   // 5: grpc.GetSortedEmployeesResponse
	(*GetEldestEmployeeRequest)(nil),     // 6: grpc.GetEldestEmployeeRequest
	(*GetEldestEmployeeResponse)(nil),    // 7: grpc.GetEldestEmployeeResponse
	(*GetMedianOfSalariesRequest)(nil),   // 8: grpc.GetMedianOfSalariesRequest
	(*GetMedianOfSalariesResponse)(nil),  // 9: grpc.GetMedianOfSalariesResponse
	(*GetAverageOfSalariesRequest)(nil),  // 10: grpc.GetAverageOfSalariesRequest
	(*GetAverageOfSalariesResponse)(nil), // 11: grpc.GetAverageOfSalariesResponse
	(*GetHighestPaidRequest)(nil),        // 12: grpc.GetHighestPaidRequest
	(*GetHighestPaidResponse)(nil),       // 13: grpc.GetHighestPaidResponse
}
var file_mgidEmployee_proto_depIdxs = []int32{
	0,  // 0: grpc.GetSortedEmployeesResponse.employee:type_name -> grpc.Employee
	0,  // 1: grpc.GetEldestEmployeeResponse.employee:type_name -> grpc.Employee
	0,  // 2: grpc.GetHighestPaidResponse.employee:type_name -> grpc.Employee
	2,  // 3: grpc.EmployeeService.GetImitatedTimeout:input_type -> grpc.GetImitatedTimeoutRequest
	4,  // 4: grpc.EmployeeService.GetSortedEmployees:input_type -> grpc.GetSortedEmployeesRequest
	6,  // 5: grpc.EmployeeService.GetEldestEmployee:input_type -> grpc.GetEldestEmployeeRequest
	8,  // 6: grpc.EmployeeService.GetMedianOfSalaries:input_type -> grpc.GetMedianOfSalariesRequest
	10, // 7: grpc.EmployeeService.GetAverageOfSalaries:input_type -> grpc.GetAverageOfSalariesRequest
	12, // 8: grpc.EmployeeService.GetHighestPaid:input_type -> grpc.GetHighestPaidRequest
	1,  // 9: grpc.EmployeeService.GetImitatedTimeout:output_type -> grpc.Empty
	5,  // 10: grpc.EmployeeService.GetSortedEmployees:output_type -> grpc.GetSortedEmployeesResponse
	7,  // 11: grpc.EmployeeService.GetEldestEmployee:output_type -> grpc.GetEldestEmployeeResponse
	9,  // 12: grpc.EmployeeService.GetMedianOfSalaries:output_type -> grpc.GetMedianOfSalariesResponse
	11, // 13: grpc.EmployeeService.GetAverageOfSalaries:output_type -> grpc.GetAverageOfSalariesResponse
	13, // 14: grpc.EmployeeService.GetHighestPaid:output_type -> grpc.GetHighestPaidResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_mgidEmployee_proto_init() }
func file_mgidEmployee_proto_init() {
	if File_mgidEmployee_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mgidEmployee_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Employee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImitatedTimeoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImitatedTimeoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSortedEmployeesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSortedEmployeesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEldestEmployeeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEldestEmployeeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedianOfSalariesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedianOfSalariesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAverageOfSalariesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAverageOfSalariesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHighestPaidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgidEmployee_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHighestPaidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mgidEmployee_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mgidEmployee_proto_goTypes,
		DependencyIndexes: file_mgidEmployee_proto_depIdxs,
		MessageInfos:      file_mgidEmployee_proto_msgTypes,
	}.Build()
	File_mgidEmployee_proto = out.File
	file_mgidEmployee_proto_rawDesc = nil
	file_mgidEmployee_proto_goTypes = nil
	file_mgidEmployee_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	GetImitatedTimeout(ctx context.Context, in *GetImitatedTimeoutRequest, opts ...grpc.CallOption) (*Empty, error)
	GetSortedEmployees(ctx context.Context, in *GetSortedEmployeesRequest, opts ...grpc.CallOption) (*GetSortedEmployeesResponse, error)
	GetEldestEmployee(ctx context.Context, in *GetEldestEmployeeRequest, opts ...grpc.CallOption) (*GetEldestEmployeeResponse, error)
	GetMedianOfSalaries(ctx context.Context, in *GetMedianOfSalariesRequest, opts ...grpc.CallOption) (*GetMedianOfSalariesResponse, error)
	GetAverageOfSalaries(ctx context.Context, in *GetAverageOfSalariesRequest, opts ...grpc.CallOption) (*GetAverageOfSalariesResponse, error)
	GetHighestPaid(ctx context.Context, in *GetHighestPaidRequest, opts ...grpc.CallOption) (*GetHighestPaidResponse, error)
}

type employeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeServiceClient(cc grpc.ClientConnInterface) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) GetImitatedTimeout(ctx context.Context, in *GetImitatedTimeoutRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/grpc.EmployeeService/GetImitatedTimeout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetSortedEmployees(ctx context.Context, in *GetSortedEmployeesRequest, opts ...grpc.CallOption) (*GetSortedEmployeesResponse, error) {
	out := new(GetSortedEmployeesResponse)
	err := c.cc.Invoke(ctx, "/grpc.EmployeeService/GetSortedEmployees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetEldestEmployee(ctx context.Context, in *GetEldestEmployeeRequest, opts ...grpc.CallOption) (*GetEldestEmployeeResponse, error) {
	out := new(GetEldestEmployeeResponse)
	err := c.cc.Invoke(ctx, "/grpc.EmployeeService/GetEldestEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetMedianOfSalaries(ctx context.Context, in *GetMedianOfSalariesRequest, opts ...grpc.CallOption) (*GetMedianOfSalariesResponse, error) {
	out := new(GetMedianOfSalariesResponse)
	err := c.cc.Invoke(ctx, "/grpc.EmployeeService/GetMedianOfSalaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetAverageOfSalaries(ctx context.Context, in *GetAverageOfSalariesRequest, opts ...grpc.CallOption) (*GetAverageOfSalariesResponse, error) {
	out := new(GetAverageOfSalariesResponse)
	err := c.cc.Invoke(ctx, "/grpc.EmployeeService/GetAverageOfSalaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetHighestPaid(ctx context.Context, in *GetHighestPaidRequest, opts ...grpc.CallOption) (*GetHighestPaidResponse, error) {
	out := new(GetHighestPaidResponse)
	err := c.cc.Invoke(ctx, "/grpc.EmployeeService/GetHighestPaid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
type EmployeeServiceServer interface {
	GetImitatedTimeout(context.Context, *GetImitatedTimeoutRequest) (*Empty, error)
	GetSortedEmployees(context.Context, *GetSortedEmployeesRequest) (*GetSortedEmployeesResponse, error)
	GetEldestEmployee(context.Context, *GetEldestEmployeeRequest) (*GetEldestEmployeeResponse, error)
	GetMedianOfSalaries(context.Context, *GetMedianOfSalariesRequest) (*GetMedianOfSalariesResponse, error)
	GetAverageOfSalaries(context.Context, *GetAverageOfSalariesRequest) (*GetAverageOfSalariesResponse, error)
	GetHighestPaid(context.Context, *GetHighestPaidRequest) (*GetHighestPaidResponse, error)
}

// UnimplementedEmployeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (*UnimplementedEmployeeServiceServer) GetImitatedTimeout(context.Context, *GetImitatedTimeoutRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImitatedTimeout not implemented")
}
func (*UnimplementedEmployeeServiceServer) GetSortedEmployees(context.Context, *GetSortedEmployeesRequest) (*GetSortedEmployeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSortedEmployees not implemented")
}
func (*UnimplementedEmployeeServiceServer) GetEldestEmployee(context.Context, *GetEldestEmployeeRequest) (*GetEldestEmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEldestEmployee not implemented")
}
func (*UnimplementedEmployeeServiceServer) GetMedianOfSalaries(context.Context, *GetMedianOfSalariesRequest) (*GetMedianOfSalariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedianOfSalaries not implemented")
}
func (*UnimplementedEmployeeServiceServer) GetAverageOfSalaries(context.Context, *GetAverageOfSalariesRequest) (*GetAverageOfSalariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAverageOfSalaries not implemented")
}
func (*UnimplementedEmployeeServiceServer) GetHighestPaid(context.Context, *GetHighestPaidRequest) (*GetHighestPaidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHighestPaid not implemented")
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_GetImitatedTimeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImitatedTimeoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetImitatedTimeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.EmployeeService/GetImitatedTimeout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetImitatedTimeout(ctx, req.(*GetImitatedTimeoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetSortedEmployees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSortedEmployeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetSortedEmployees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.EmployeeService/GetSortedEmployees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetSortedEmployees(ctx, req.(*GetSortedEmployeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetEldestEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEldestEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetEldestEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.EmployeeService/GetEldestEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetEldestEmployee(ctx, req.(*GetEldestEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetMedianOfSalaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedianOfSalariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetMedianOfSalaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.EmployeeService/GetMedianOfSalaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetMedianOfSalaries(ctx, req.(*GetMedianOfSalariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetAverageOfSalaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAverageOfSalariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetAverageOfSalaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.EmployeeService/GetAverageOfSalaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetAverageOfSalaries(ctx, req.(*GetAverageOfSalariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetHighestPaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHighestPaidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetHighestPaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.EmployeeService/GetHighestPaid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetHighestPaid(ctx, req.(*GetHighestPaidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetImitatedTimeout",
			Handler:    _EmployeeService_GetImitatedTimeout_Handler,
		},
		{
			MethodName: "GetSortedEmployees",
			Handler:    _EmployeeService_GetSortedEmployees_Handler,
		},
		{
			MethodName: "GetEldestEmployee",
			Handler:    _EmployeeService_GetEldestEmployee_Handler,
		},
		{
			MethodName: "GetMedianOfSalaries",
			Handler:    _EmployeeService_GetMedianOfSalaries_Handler,
		},
		{
			MethodName: "GetAverageOfSalaries",
			Handler:    _EmployeeService_GetAverageOfSalaries_Handler,
		},
		{
			MethodName: "GetHighestPaid",
			Handler:    _EmployeeService_GetHighestPaid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mgidEmployee.proto",
}
